version: "3.9"
services:
  web:
    build:
      context: ./web
      dockerfile: ./Dockerfile
    volumes:
      - ./web/html:/var/www/html
    ports:
      - ${WEB_PORT}:80
    depends_on:
      - mysql

  mysql:
    build:
      context: ./mysql
      dockerfile: ./Dockerfile
    volumes:
      - ./mysql/mysql:/var/lib/mysql
      - ./mysql/config/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - ${MYSQL_PORT}:3306

  phpmyadmin:
    build:
      context: ./phpmyadmin
      dockerfile: ./Dockerfile
    environment:
      PMA_HOST: "mysql"
      PMA_USER: ${PMA_USER}
      PMA_PASSWORD: ${PMA_PASSWORD}
    ports:
      - ${PMA_PORT}:80
